# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 702ab7d2766cc20f044bb88dad525a7d3cba8109082101d68cbf8b05b40b768b1587a54d9189c8801cad67afebef3c329a5e7251e1f8aa5efaec51c502c8be5b

test:
  secret_key_base: cfca9de3aadf2e72adfb7e26850cde0f2f493ab3269cb9acb865b867dc550bb73f64d760f823618636da7f01d5c65576363f58eceef154c6304e8ae75c86c4dc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
